"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_label_params import CreateLabelParams


class TestCreateLabelParams(unittest.TestCase):
    """CreateLabelParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateLabelParams(self):
        """Test CreateLabelParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateLabelParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
