"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_category_params import CreateCategoryParams


class TestCreateCategoryParams(unittest.TestCase):
    """CreateCategoryParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateCategoryParams(self):
        """Test CreateCategoryParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateCategoryParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
