"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_file_obj import CreateFileObj


class TestCreateFileObj(unittest.TestCase):
    """CreateFileObj unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateFileObj(self):
        """Test CreateFileObj"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateFileObj()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
