"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.project_stats import ProjectStats


class TestProjectStats(unittest.TestCase):
    """ProjectStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectStats(self):
        """Test ProjectStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
