"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.workflow import Workflow
globals()['Workflow'] = Workflow
from clubhouse_python_sdk.model.team import Team


class TestTeam(unittest.TestCase):
    """Team unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeam(self):
        """Test Team"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Team()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
