"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.epic_stats import EpicStats


class TestEpicStats(unittest.TestCase):
    """EpicStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEpicStats(self):
        """Test EpicStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EpicStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
