"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_entity_template_external_ticket import CreateEntityTemplateExternalTicket
from clubhouse_python_sdk.model.create_label_params import CreateLabelParams
from clubhouse_python_sdk.model.entity_template_task import EntityTemplateTask
from clubhouse_python_sdk.model.file import File
from clubhouse_python_sdk.model.linked_file import LinkedFile
globals()['CreateEntityTemplateExternalTicket'] = CreateEntityTemplateExternalTicket
globals()['CreateLabelParams'] = CreateLabelParams
globals()['EntityTemplateTask'] = EntityTemplateTask
globals()['File'] = File
globals()['LinkedFile'] = LinkedFile
from clubhouse_python_sdk.model.create_story_contents import CreateStoryContents


class TestCreateStoryContents(unittest.TestCase):
    """CreateStoryContents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateStoryContents(self):
        """Test CreateStoryContents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateStoryContents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
