"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_label_params import CreateLabelParams
globals()['CreateLabelParams'] = CreateLabelParams
from clubhouse_python_sdk.model.create_iteration import CreateIteration


class TestCreateIteration(unittest.TestCase):
    """CreateIteration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateIteration(self):
        """Test CreateIteration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateIteration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
