"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.reaction import Reaction
globals()['Reaction'] = Reaction
from clubhouse_python_sdk.model.comment import Comment


class TestComment(unittest.TestCase):
    """Comment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComment(self):
        """Test Comment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Comment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
