"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_story_link_params import CreateStoryLinkParams


class TestCreateStoryLinkParams(unittest.TestCase):
    """CreateStoryLinkParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateStoryLinkParams(self):
        """Test CreateStoryLinkParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateStoryLinkParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
