"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.workflow_state import WorkflowState
globals()['WorkflowState'] = WorkflowState
from clubhouse_python_sdk.model.workflow import Workflow


class TestWorkflow(unittest.TestCase):
    """Workflow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflow(self):
        """Test Workflow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Workflow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
