"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_category_params import CreateCategoryParams
globals()['CreateCategoryParams'] = CreateCategoryParams
from clubhouse_python_sdk.model.update_milestone import UpdateMilestone


class TestUpdateMilestone(unittest.TestCase):
    """UpdateMilestone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateMilestone(self):
        """Test UpdateMilestone"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateMilestone()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
