"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.external_ticket import ExternalTicket
from clubhouse_python_sdk.model.label import Label
from clubhouse_python_sdk.model.story_stats import StoryStats
from clubhouse_python_sdk.model.support_ticket import SupportTicket
from clubhouse_python_sdk.model.typed_story_link import TypedStoryLink
globals()['ExternalTicket'] = ExternalTicket
globals()['Label'] = Label
globals()['StoryStats'] = StoryStats
globals()['SupportTicket'] = SupportTicket
globals()['TypedStoryLink'] = TypedStoryLink
from clubhouse_python_sdk.model.story_slim import StorySlim


class TestStorySlim(unittest.TestCase):
    """StorySlim unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorySlim(self):
        """Test StorySlim"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorySlim()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
