"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.get_epic_stories import GetEpicStories


class TestGetEpicStories(unittest.TestCase):
    """GetEpicStories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEpicStories(self):
        """Test GetEpicStories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEpicStories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
