"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v3_categories_category_public_id_delete(self):
        """Test case for api_v3_categories_category_public_id_delete

        Delete Category  # noqa: E501
        """
        pass

    def test_api_v3_categories_category_public_id_get(self):
        """Test case for api_v3_categories_category_public_id_get

        Get Category  # noqa: E501
        """
        pass

    def test_api_v3_categories_category_public_id_milestones_get(self):
        """Test case for api_v3_categories_category_public_id_milestones_get

        List Category Milestones  # noqa: E501
        """
        pass

    def test_api_v3_categories_category_public_id_put(self):
        """Test case for api_v3_categories_category_public_id_put

        Update Category  # noqa: E501
        """
        pass

    def test_api_v3_categories_get(self):
        """Test case for api_v3_categories_get

        List Categories  # noqa: E501
        """
        pass

    def test_api_v3_categories_post(self):
        """Test case for api_v3_categories_post

        Create Category  # noqa: E501
        """
        pass

    def test_api_v3_entity_templates_disable_put(self):
        """Test case for api_v3_entity_templates_disable_put

        Disable Story Templates  # noqa: E501
        """
        pass

    def test_api_v3_entity_templates_enable_put(self):
        """Test case for api_v3_entity_templates_enable_put

        Enable Story Templates  # noqa: E501
        """
        pass

    def test_api_v3_entity_templates_entity_template_public_id_delete(self):
        """Test case for api_v3_entity_templates_entity_template_public_id_delete

        Delete Entity Template  # noqa: E501
        """
        pass

    def test_api_v3_entity_templates_entity_template_public_id_get(self):
        """Test case for api_v3_entity_templates_entity_template_public_id_get

        Get Entity Template  # noqa: E501
        """
        pass

    def test_api_v3_entity_templates_entity_template_public_id_put(self):
        """Test case for api_v3_entity_templates_entity_template_public_id_put

        Update Entity Template  # noqa: E501
        """
        pass

    def test_api_v3_entity_templates_get(self):
        """Test case for api_v3_entity_templates_get

        List Entity Templates.  # noqa: E501
        """
        pass

    def test_api_v3_entity_templates_post(self):
        """Test case for api_v3_entity_templates_post

        Create Entity Template  # noqa: E501
        """
        pass

    def test_api_v3_epic_workflow_get(self):
        """Test case for api_v3_epic_workflow_get

        Get Epic Workflow  # noqa: E501
        """
        pass

    def test_api_v3_epics_epic_public_id_comments_comment_public_id_delete(self):
        """Test case for api_v3_epics_epic_public_id_comments_comment_public_id_delete

        Delete Epic Comment  # noqa: E501
        """
        pass

    def test_api_v3_epics_epic_public_id_comments_comment_public_id_get(self):
        """Test case for api_v3_epics_epic_public_id_comments_comment_public_id_get

        Get Epic Comment  # noqa: E501
        """
        pass

    def test_api_v3_epics_epic_public_id_comments_comment_public_id_post(self):
        """Test case for api_v3_epics_epic_public_id_comments_comment_public_id_post

        Create Epic Comment Comment  # noqa: E501
        """
        pass

    def test_api_v3_epics_epic_public_id_comments_comment_public_id_put(self):
        """Test case for api_v3_epics_epic_public_id_comments_comment_public_id_put

        Update Epic Comment  # noqa: E501
        """
        pass

    def test_api_v3_epics_epic_public_id_comments_get(self):
        """Test case for api_v3_epics_epic_public_id_comments_get

        List Epic Comments  # noqa: E501
        """
        pass

    def test_api_v3_epics_epic_public_id_comments_post(self):
        """Test case for api_v3_epics_epic_public_id_comments_post

        Create Epic Comment  # noqa: E501
        """
        pass

    def test_api_v3_epics_epic_public_id_delete(self):
        """Test case for api_v3_epics_epic_public_id_delete

        Delete Epic  # noqa: E501
        """
        pass

    def test_api_v3_epics_epic_public_id_get(self):
        """Test case for api_v3_epics_epic_public_id_get

        Get Epic  # noqa: E501
        """
        pass

    def test_api_v3_epics_epic_public_id_put(self):
        """Test case for api_v3_epics_epic_public_id_put

        Update Epic  # noqa: E501
        """
        pass

    def test_api_v3_epics_epic_public_id_stories_get(self):
        """Test case for api_v3_epics_epic_public_id_stories_get

        List Epic Stories  # noqa: E501
        """
        pass

    def test_api_v3_epics_get(self):
        """Test case for api_v3_epics_get

        List Epics  # noqa: E501
        """
        pass

    def test_api_v3_epics_post(self):
        """Test case for api_v3_epics_post

        Create Epic  # noqa: E501
        """
        pass

    def test_api_v3_files_file_public_id_delete(self):
        """Test case for api_v3_files_file_public_id_delete

        Delete File  # noqa: E501
        """
        pass

    def test_api_v3_files_file_public_id_get(self):
        """Test case for api_v3_files_file_public_id_get

        Get File  # noqa: E501
        """
        pass

    def test_api_v3_files_file_public_id_put(self):
        """Test case for api_v3_files_file_public_id_put

        Update File  # noqa: E501
        """
        pass

    def test_api_v3_files_get(self):
        """Test case for api_v3_files_get

        List Files  # noqa: E501
        """
        pass

    def test_api_v3_files_post(self):
        """Test case for api_v3_files_post

        Create Files  # noqa: E501
        """
        pass

    def test_api_v3_groups_disable_put(self):
        """Test case for api_v3_groups_disable_put

        Disable Groups  # noqa: E501
        """
        pass

    def test_api_v3_groups_enable_put(self):
        """Test case for api_v3_groups_enable_put

        Enable Groups  # noqa: E501
        """
        pass

    def test_api_v3_groups_get(self):
        """Test case for api_v3_groups_get

        List Groups  # noqa: E501
        """
        pass

    def test_api_v3_groups_group_public_id_get(self):
        """Test case for api_v3_groups_group_public_id_get

        Get Group  # noqa: E501
        """
        pass

    def test_api_v3_groups_group_public_id_put(self):
        """Test case for api_v3_groups_group_public_id_put

        Update Group  # noqa: E501
        """
        pass

    def test_api_v3_groups_post(self):
        """Test case for api_v3_groups_post

        Create Group  # noqa: E501
        """
        pass

    def test_api_v3_iterations_disable_put(self):
        """Test case for api_v3_iterations_disable_put

        Disable Iterations  # noqa: E501
        """
        pass

    def test_api_v3_iterations_enable_put(self):
        """Test case for api_v3_iterations_enable_put

        Enable Iterations  # noqa: E501
        """
        pass

    def test_api_v3_iterations_get(self):
        """Test case for api_v3_iterations_get

        List Iterations  # noqa: E501
        """
        pass

    def test_api_v3_iterations_iteration_public_id_delete(self):
        """Test case for api_v3_iterations_iteration_public_id_delete

        Delete Iteration  # noqa: E501
        """
        pass

    def test_api_v3_iterations_iteration_public_id_get(self):
        """Test case for api_v3_iterations_iteration_public_id_get

        Get Iteration  # noqa: E501
        """
        pass

    def test_api_v3_iterations_iteration_public_id_put(self):
        """Test case for api_v3_iterations_iteration_public_id_put

        Update Iteration  # noqa: E501
        """
        pass

    def test_api_v3_iterations_iteration_public_id_stories_get(self):
        """Test case for api_v3_iterations_iteration_public_id_stories_get

        List Iteration Stories  # noqa: E501
        """
        pass

    def test_api_v3_iterations_post(self):
        """Test case for api_v3_iterations_post

        Create Iteration  # noqa: E501
        """
        pass

    def test_api_v3_labels_get(self):
        """Test case for api_v3_labels_get

        List Labels  # noqa: E501
        """
        pass

    def test_api_v3_labels_label_public_id_delete(self):
        """Test case for api_v3_labels_label_public_id_delete

        Delete Label  # noqa: E501
        """
        pass

    def test_api_v3_labels_label_public_id_epics_get(self):
        """Test case for api_v3_labels_label_public_id_epics_get

        List Label Epics  # noqa: E501
        """
        pass

    def test_api_v3_labels_label_public_id_get(self):
        """Test case for api_v3_labels_label_public_id_get

        Get Label  # noqa: E501
        """
        pass

    def test_api_v3_labels_label_public_id_put(self):
        """Test case for api_v3_labels_label_public_id_put

        Update Label  # noqa: E501
        """
        pass

    def test_api_v3_labels_label_public_id_stories_get(self):
        """Test case for api_v3_labels_label_public_id_stories_get

        List Label Stories  # noqa: E501
        """
        pass

    def test_api_v3_labels_post(self):
        """Test case for api_v3_labels_post

        Create Label  # noqa: E501
        """
        pass

    def test_api_v3_linked_files_get(self):
        """Test case for api_v3_linked_files_get

        List Linked Files  # noqa: E501
        """
        pass

    def test_api_v3_linked_files_linked_file_public_id_delete(self):
        """Test case for api_v3_linked_files_linked_file_public_id_delete

        Delete Linked File  # noqa: E501
        """
        pass

    def test_api_v3_linked_files_linked_file_public_id_get(self):
        """Test case for api_v3_linked_files_linked_file_public_id_get

        Get Linked File  # noqa: E501
        """
        pass

    def test_api_v3_linked_files_linked_file_public_id_put(self):
        """Test case for api_v3_linked_files_linked_file_public_id_put

        Update Linked File  # noqa: E501
        """
        pass

    def test_api_v3_linked_files_post(self):
        """Test case for api_v3_linked_files_post

        Create Linked File  # noqa: E501
        """
        pass

    def test_api_v3_member_get(self):
        """Test case for api_v3_member_get

        Get Current Member Info  # noqa: E501
        """
        pass

    def test_api_v3_members_get(self):
        """Test case for api_v3_members_get

        List Members  # noqa: E501
        """
        pass

    def test_api_v3_members_member_public_id_get(self):
        """Test case for api_v3_members_member_public_id_get

        Get Member  # noqa: E501
        """
        pass

    def test_api_v3_milestones_get(self):
        """Test case for api_v3_milestones_get

        List Milestones  # noqa: E501
        """
        pass

    def test_api_v3_milestones_milestone_public_id_delete(self):
        """Test case for api_v3_milestones_milestone_public_id_delete

        Delete Milestone  # noqa: E501
        """
        pass

    def test_api_v3_milestones_milestone_public_id_epics_get(self):
        """Test case for api_v3_milestones_milestone_public_id_epics_get

        List Milestone Epics  # noqa: E501
        """
        pass

    def test_api_v3_milestones_milestone_public_id_get(self):
        """Test case for api_v3_milestones_milestone_public_id_get

        Get Milestone  # noqa: E501
        """
        pass

    def test_api_v3_milestones_milestone_public_id_put(self):
        """Test case for api_v3_milestones_milestone_public_id_put

        Update Milestone  # noqa: E501
        """
        pass

    def test_api_v3_milestones_post(self):
        """Test case for api_v3_milestones_post

        Create Milestone  # noqa: E501
        """
        pass

    def test_api_v3_projects_get(self):
        """Test case for api_v3_projects_get

        List Projects  # noqa: E501
        """
        pass

    def test_api_v3_projects_post(self):
        """Test case for api_v3_projects_post

        Create Project  # noqa: E501
        """
        pass

    def test_api_v3_projects_project_public_id_delete(self):
        """Test case for api_v3_projects_project_public_id_delete

        Delete Project  # noqa: E501
        """
        pass

    def test_api_v3_projects_project_public_id_get(self):
        """Test case for api_v3_projects_project_public_id_get

        Get Project  # noqa: E501
        """
        pass

    def test_api_v3_projects_project_public_id_put(self):
        """Test case for api_v3_projects_project_public_id_put

        Update Project  # noqa: E501
        """
        pass

    def test_api_v3_projects_project_public_id_stories_get(self):
        """Test case for api_v3_projects_project_public_id_stories_get

        List Stories  # noqa: E501
        """
        pass

    def test_api_v3_repositories_get(self):
        """Test case for api_v3_repositories_get

        List Repositories  # noqa: E501
        """
        pass

    def test_api_v3_repositories_repo_public_id_get(self):
        """Test case for api_v3_repositories_repo_public_id_get

        Get Repository  # noqa: E501
        """
        pass

    def test_api_v3_search_epics_get(self):
        """Test case for api_v3_search_epics_get

        Search Epics  # noqa: E501
        """
        pass

    def test_api_v3_search_get(self):
        """Test case for api_v3_search_get

        Search  # noqa: E501
        """
        pass

    def test_api_v3_search_stories_get(self):
        """Test case for api_v3_search_stories_get

        Search Stories  # noqa: E501
        """
        pass

    def test_api_v3_stories_bulk_delete(self):
        """Test case for api_v3_stories_bulk_delete

        Delete Multiple Stories  # noqa: E501
        """
        pass

    def test_api_v3_stories_bulk_post(self):
        """Test case for api_v3_stories_bulk_post

        Create Multiple Stories  # noqa: E501
        """
        pass

    def test_api_v3_stories_bulk_put(self):
        """Test case for api_v3_stories_bulk_put

        Update Multiple Stories  # noqa: E501
        """
        pass

    def test_api_v3_stories_post(self):
        """Test case for api_v3_stories_post

        Create Story  # noqa: E501
        """
        pass

    def test_api_v3_stories_search_post(self):
        """Test case for api_v3_stories_search_post

        Search Stories (Old)  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_comments_comment_public_id_delete(self):
        """Test case for api_v3_stories_story_public_id_comments_comment_public_id_delete

        Delete Comment  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_comments_comment_public_id_get(self):
        """Test case for api_v3_stories_story_public_id_comments_comment_public_id_get

        Get Comment  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_comments_comment_public_id_put(self):
        """Test case for api_v3_stories_story_public_id_comments_comment_public_id_put

        Update Comment  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_comments_comment_public_id_reactions_delete(self):
        """Test case for api_v3_stories_story_public_id_comments_comment_public_id_reactions_delete

        Delete Reaction  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_comments_comment_public_id_reactions_post(self):
        """Test case for api_v3_stories_story_public_id_comments_comment_public_id_reactions_post

        Create Reaction  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_comments_post(self):
        """Test case for api_v3_stories_story_public_id_comments_post

        Create Comment  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_delete(self):
        """Test case for api_v3_stories_story_public_id_delete

        Delete Story  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_get(self):
        """Test case for api_v3_stories_story_public_id_get

        Get Story  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_put(self):
        """Test case for api_v3_stories_story_public_id_put

        Update Story  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_tasks_post(self):
        """Test case for api_v3_stories_story_public_id_tasks_post

        Create Task  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_tasks_task_public_id_delete(self):
        """Test case for api_v3_stories_story_public_id_tasks_task_public_id_delete

        Delete Task  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_tasks_task_public_id_get(self):
        """Test case for api_v3_stories_story_public_id_tasks_task_public_id_get

        Get Task  # noqa: E501
        """
        pass

    def test_api_v3_stories_story_public_id_tasks_task_public_id_put(self):
        """Test case for api_v3_stories_story_public_id_tasks_task_public_id_put

        Update Task  # noqa: E501
        """
        pass

    def test_api_v3_story_links_post(self):
        """Test case for api_v3_story_links_post

        Create Story Link  # noqa: E501
        """
        pass

    def test_api_v3_story_links_story_link_public_id_delete(self):
        """Test case for api_v3_story_links_story_link_public_id_delete

        Delete Story Link  # noqa: E501
        """
        pass

    def test_api_v3_story_links_story_link_public_id_get(self):
        """Test case for api_v3_story_links_story_link_public_id_get

        Get Story Link  # noqa: E501
        """
        pass

    def test_api_v3_story_links_story_link_public_id_put(self):
        """Test case for api_v3_story_links_story_link_public_id_put

        Update Story Link  # noqa: E501
        """
        pass

    def test_api_v3_teams_get(self):
        """Test case for api_v3_teams_get

        List Teams  # noqa: E501
        """
        pass

    def test_api_v3_teams_team_public_id_get(self):
        """Test case for api_v3_teams_team_public_id_get

        Get Team  # noqa: E501
        """
        pass

    def test_api_v3_workflows_get(self):
        """Test case for api_v3_workflows_get

        List Workflows  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
