"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.story_contents import StoryContents
globals()['StoryContents'] = StoryContents
from clubhouse_python_sdk.model.entity_template import EntityTemplate


class TestEntityTemplate(unittest.TestCase):
    """EntityTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityTemplate(self):
        """Test EntityTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
