"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.pull_request_label import PullRequestLabel
globals()['PullRequestLabel'] = PullRequestLabel
from clubhouse_python_sdk.model.pull_request import PullRequest


class TestPullRequest(unittest.TestCase):
    """PullRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPullRequest(self):
        """Test PullRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PullRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
