"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.get_project_stories import GetProjectStories


class TestGetProjectStories(unittest.TestCase):
    """GetProjectStories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetProjectStories(self):
        """Test GetProjectStories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetProjectStories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
