"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_task_params import CreateTaskParams


class TestCreateTaskParams(unittest.TestCase):
    """CreateTaskParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTaskParams(self):
        """Test CreateTaskParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTaskParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
