"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.epic_stats import EpicStats
from clubhouse_python_sdk.model.external_ticket import ExternalTicket
from clubhouse_python_sdk.model.label import Label
from clubhouse_python_sdk.model.support_ticket import SupportTicket
globals()['EpicStats'] = EpicStats
globals()['ExternalTicket'] = ExternalTicket
globals()['Label'] = Label
globals()['SupportTicket'] = SupportTicket
from clubhouse_python_sdk.model.epic_slim import EpicSlim


class TestEpicSlim(unittest.TestCase):
    """EpicSlim unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEpicSlim(self):
        """Test EpicSlim"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EpicSlim()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
