"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_epic_comment import CreateEpicComment


class TestCreateEpicComment(unittest.TestCase):
    """CreateEpicComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateEpicComment(self):
        """Test CreateEpicComment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateEpicComment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
