"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.typed_story_link import TypedStoryLink


class TestTypedStoryLink(unittest.TestCase):
    """TypedStoryLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypedStoryLink(self):
        """Test TypedStoryLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TypedStoryLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
