"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.label_stats import LabelStats
globals()['LabelStats'] = LabelStats
from clubhouse_python_sdk.model.label import Label


class TestLabel(unittest.TestCase):
    """Label unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabel(self):
        """Test Label"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Label()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
