"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_or_delete_reaction import CreateOrDeleteReaction


class TestCreateOrDeleteReaction(unittest.TestCase):
    """CreateOrDeleteReaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateOrDeleteReaction(self):
        """Test CreateOrDeleteReaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateOrDeleteReaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
