"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.profile import Profile
globals()['Profile'] = Profile
from clubhouse_python_sdk.model.member import Member


class TestMember(unittest.TestCase):
    """Member unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMember(self):
        """Test Member"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Member()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
