"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.story_stats import StoryStats


class TestStoryStats(unittest.TestCase):
    """StoryStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoryStats(self):
        """Test StoryStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StoryStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
