"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_label_params import CreateLabelParams
globals()['CreateLabelParams'] = CreateLabelParams
from clubhouse_python_sdk.model.update_story import UpdateStory


class TestUpdateStory(unittest.TestCase):
    """UpdateStory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateStory(self):
        """Test UpdateStory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateStory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
