"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.icon import Icon
globals()['Icon'] = Icon
from clubhouse_python_sdk.model.group import Group


class TestGroup(unittest.TestCase):
    """Group unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroup(self):
        """Test Group"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Group()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
