"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.identity import Identity
globals()['Identity'] = Identity
from clubhouse_python_sdk.model.commit import Commit


class TestCommit(unittest.TestCase):
    """Commit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommit(self):
        """Test Commit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Commit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
