"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.delete_stories import DeleteStories


class TestDeleteStories(unittest.TestCase):
    """DeleteStories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteStories(self):
        """Test DeleteStories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteStories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
