"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.list_labels import ListLabels


class TestListLabels(unittest.TestCase):
    """ListLabels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListLabels(self):
        """Test ListLabels"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListLabels()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
