"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_external_ticket_params import CreateExternalTicketParams
from clubhouse_python_sdk.model.create_label_params import CreateLabelParams
from clubhouse_python_sdk.model.create_story_comment_params import CreateStoryCommentParams
from clubhouse_python_sdk.model.create_story_link_params import CreateStoryLinkParams
from clubhouse_python_sdk.model.create_task_params import CreateTaskParams
globals()['CreateExternalTicketParams'] = CreateExternalTicketParams
globals()['CreateLabelParams'] = CreateLabelParams
globals()['CreateStoryCommentParams'] = CreateStoryCommentParams
globals()['CreateStoryLinkParams'] = CreateStoryLinkParams
globals()['CreateTaskParams'] = CreateTaskParams
from clubhouse_python_sdk.model.create_story_params import CreateStoryParams


class TestCreateStoryParams(unittest.TestCase):
    """CreateStoryParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateStoryParams(self):
        """Test CreateStoryParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateStoryParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
