"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.epic_stats import EpicStats
from clubhouse_python_sdk.model.external_ticket import ExternalTicket
from clubhouse_python_sdk.model.label import Label
from clubhouse_python_sdk.model.support_ticket import SupportTicket
from clubhouse_python_sdk.model.threaded_comment import ThreadedComment
globals()['EpicStats'] = EpicStats
globals()['ExternalTicket'] = ExternalTicket
globals()['Label'] = Label
globals()['SupportTicket'] = SupportTicket
globals()['ThreadedComment'] = ThreadedComment
from clubhouse_python_sdk.model.epic import Epic


class TestEpic(unittest.TestCase):
    """Epic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEpic(self):
        """Test Epic"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Epic()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
