"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.list_members import ListMembers


class TestListMembers(unittest.TestCase):
    """ListMembers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListMembers(self):
        """Test ListMembers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListMembers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
