"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.list_epics import ListEpics


class TestListEpics(unittest.TestCase):
    """ListEpics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListEpics(self):
        """Test ListEpics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListEpics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
