"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_external_ticket_params import CreateExternalTicketParams


class TestCreateExternalTicketParams(unittest.TestCase):
    """CreateExternalTicketParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateExternalTicketParams(self):
        """Test CreateExternalTicketParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateExternalTicketParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
