"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.basic_workspace_info import BasicWorkspaceInfo
globals()['BasicWorkspaceInfo'] = BasicWorkspaceInfo
from clubhouse_python_sdk.model.member_info import MemberInfo


class TestMemberInfo(unittest.TestCase):
    """MemberInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMemberInfo(self):
        """Test MemberInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MemberInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
