"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_task import CreateTask


class TestCreateTask(unittest.TestCase):
    """CreateTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTask(self):
        """Test CreateTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
