"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_story_contents import CreateStoryContents
globals()['CreateStoryContents'] = CreateStoryContents
from clubhouse_python_sdk.model.update_entity_template import UpdateEntityTemplate


class TestUpdateEntityTemplate(unittest.TestCase):
    """UpdateEntityTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateEntityTemplate(self):
        """Test UpdateEntityTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateEntityTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
