"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_category_params import CreateCategoryParams
globals()['CreateCategoryParams'] = CreateCategoryParams
from clubhouse_python_sdk.model.create_milestone import CreateMilestone


class TestCreateMilestone(unittest.TestCase):
    """CreateMilestone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateMilestone(self):
        """Test CreateMilestone"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateMilestone()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
