"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.label_stats import LabelStats


class TestLabelStats(unittest.TestCase):
    """LabelStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelStats(self):
        """Test LabelStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LabelStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
