"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.story_contents_task import StoryContentsTask


class TestStoryContentsTask(unittest.TestCase):
    """StoryContentsTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoryContentsTask(self):
        """Test StoryContentsTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StoryContentsTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
