"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_label_params import CreateLabelParams
globals()['CreateLabelParams'] = CreateLabelParams
from clubhouse_python_sdk.model.update_epic import UpdateEpic


class TestUpdateEpic(unittest.TestCase):
    """UpdateEpic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateEpic(self):
        """Test UpdateEpic"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateEpic()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
