"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.epic_state import EpicState


class TestEpicState(unittest.TestCase):
    """EpicState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEpicState(self):
        """Test EpicState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EpicState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
