"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.iteration_stats import IterationStats
from clubhouse_python_sdk.model.label import Label
globals()['IterationStats'] = IterationStats
globals()['Label'] = Label
from clubhouse_python_sdk.model.iteration import Iteration


class TestIteration(unittest.TestCase):
    """Iteration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIteration(self):
        """Test Iteration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Iteration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
