"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.category import Category
from clubhouse_python_sdk.model.milestone_stats import MilestoneStats
globals()['Category'] = Category
globals()['MilestoneStats'] = MilestoneStats
from clubhouse_python_sdk.model.milestone import Milestone


class TestMilestone(unittest.TestCase):
    """Milestone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMilestone(self):
        """Test Milestone"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Milestone()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
