"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.pull_request import PullRequest
globals()['PullRequest'] = PullRequest
from clubhouse_python_sdk.model.branch import Branch


class TestBranch(unittest.TestCase):
    """Branch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBranch(self):
        """Test Branch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Branch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
