"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import clubhouse_python_sdk
from clubhouse_python_sdk.model.create_story_params import CreateStoryParams
globals()['CreateStoryParams'] = CreateStoryParams
from clubhouse_python_sdk.model.create_stories import CreateStories


class TestCreateStories(unittest.TestCase):
    """CreateStories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateStories(self):
        """Test CreateStories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateStories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
