"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from clubhouse_python_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from clubhouse_python_sdk.model.identity import Identity
    globals()['Identity'] = Identity


class Commit(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'author_email': (str,),  # noqa: E501
            'author_id': (str, none_type,),  # noqa: E501
            'author_identity': (Identity,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'entity_type': (str,),  # noqa: E501
            'hash': (str,),  # noqa: E501
            'id': (int, none_type,),  # noqa: E501
            'merged_branch_ids': ([int],),  # noqa: E501
            'message': (str,),  # noqa: E501
            'repository_id': (int, none_type,),  # noqa: E501
            'timestamp': (datetime,),  # noqa: E501
            'updated_at': (datetime, none_type,),  # noqa: E501
            'url': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'author_email': 'author_email',  # noqa: E501
        'author_id': 'author_id',  # noqa: E501
        'author_identity': 'author_identity',  # noqa: E501
        'created_at': 'created_at',  # noqa: E501
        'entity_type': 'entity_type',  # noqa: E501
        'hash': 'hash',  # noqa: E501
        'id': 'id',  # noqa: E501
        'merged_branch_ids': 'merged_branch_ids',  # noqa: E501
        'message': 'message',  # noqa: E501
        'repository_id': 'repository_id',  # noqa: E501
        'timestamp': 'timestamp',  # noqa: E501
        'updated_at': 'updated_at',  # noqa: E501
        'url': 'url',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, author_email, author_id, author_identity, created_at, entity_type, hash, id, merged_branch_ids, message, repository_id, timestamp, updated_at, url, *args, **kwargs):  # noqa: E501
        """Commit - a model defined in OpenAPI

        Args:
            author_email (str): The email address of the VCS user that authored the Commit.
            author_id (str, none_type): The ID of the Member that authored the Commit, if known.
            author_identity (Identity):
            created_at (datetime): The time/date the Commit was created.
            entity_type (str): A string description of this resource.
            hash (str): The Commit hash.
            id (int, none_type): The unique ID of the Commit.
            merged_branch_ids ([int]): The IDs of the Branches the Commit has been merged into.
            message (str): The Commit message.
            repository_id (int, none_type): The ID of the Repository that contains the Commit.
            timestamp (datetime): The time/date the Commit was pushed.
            updated_at (datetime, none_type): The time/date the Commit was updated.
            url (str): The URL of the Commit.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.author_email = author_email
        self.author_id = author_id
        self.author_identity = author_identity
        self.created_at = created_at
        self.entity_type = entity_type
        self.hash = hash
        self.id = id
        self.merged_branch_ids = merged_branch_ids
        self.message = message
        self.repository_id = repository_id
        self.timestamp = timestamp
        self.updated_at = updated_at
        self.url = url
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
