"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from clubhouse_python_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from clubhouse_python_sdk.model.create_external_ticket_params import CreateExternalTicketParams
    from clubhouse_python_sdk.model.create_label_params import CreateLabelParams
    from clubhouse_python_sdk.model.create_story_comment_params import CreateStoryCommentParams
    from clubhouse_python_sdk.model.create_story_link_params import CreateStoryLinkParams
    from clubhouse_python_sdk.model.create_task_params import CreateTaskParams
    globals()['CreateExternalTicketParams'] = CreateExternalTicketParams
    globals()['CreateLabelParams'] = CreateLabelParams
    globals()['CreateStoryCommentParams'] = CreateStoryCommentParams
    globals()['CreateStoryLinkParams'] = CreateStoryLinkParams
    globals()['CreateTaskParams'] = CreateTaskParams


class CreateStoryParams(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('story_type',): {
            'BUG': "bug",
            'CHORE': "chore",
            'FEATURE': "feature",
        },
    }

    validations = {
        ('file_ids',): {
        },
        ('follower_ids',): {
        },
        ('linked_file_ids',): {
        },
        ('owner_ids',): {
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'name': (str,),  # noqa: E501
            'project_id': (int,),  # noqa: E501
            'archived': (bool,),  # noqa: E501
            'comments': ([CreateStoryCommentParams],),  # noqa: E501
            'completed_at_override': (datetime,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'deadline': (datetime, none_type,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'epic_id': (int, none_type,),  # noqa: E501
            'estimate': (int, none_type,),  # noqa: E501
            'external_id': (str,),  # noqa: E501
            'external_links': ([str],),  # noqa: E501
            'external_tickets': ([CreateExternalTicketParams],),  # noqa: E501
            'file_ids': ([int],),  # noqa: E501
            'follower_ids': ([str],),  # noqa: E501
            'group_id': (str, none_type,),  # noqa: E501
            'iteration_id': (int, none_type,),  # noqa: E501
            'labels': ([CreateLabelParams],),  # noqa: E501
            'linked_file_ids': ([int],),  # noqa: E501
            'owner_ids': ([str],),  # noqa: E501
            'requested_by_id': (str,),  # noqa: E501
            'started_at_override': (datetime,),  # noqa: E501
            'story_links': ([CreateStoryLinkParams],),  # noqa: E501
            'story_type': (str,),  # noqa: E501
            'support_tickets': ([CreateExternalTicketParams],),  # noqa: E501
            'tasks': ([CreateTaskParams],),  # noqa: E501
            'updated_at': (datetime,),  # noqa: E501
            'workflow_state_id': (int,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'name': 'name',  # noqa: E501
        'project_id': 'project_id',  # noqa: E501
        'archived': 'archived',  # noqa: E501
        'comments': 'comments',  # noqa: E501
        'completed_at_override': 'completed_at_override',  # noqa: E501
        'created_at': 'created_at',  # noqa: E501
        'deadline': 'deadline',  # noqa: E501
        'description': 'description',  # noqa: E501
        'epic_id': 'epic_id',  # noqa: E501
        'estimate': 'estimate',  # noqa: E501
        'external_id': 'external_id',  # noqa: E501
        'external_links': 'external_links',  # noqa: E501
        'external_tickets': 'external_tickets',  # noqa: E501
        'file_ids': 'file_ids',  # noqa: E501
        'follower_ids': 'follower_ids',  # noqa: E501
        'group_id': 'group_id',  # noqa: E501
        'iteration_id': 'iteration_id',  # noqa: E501
        'labels': 'labels',  # noqa: E501
        'linked_file_ids': 'linked_file_ids',  # noqa: E501
        'owner_ids': 'owner_ids',  # noqa: E501
        'requested_by_id': 'requested_by_id',  # noqa: E501
        'started_at_override': 'started_at_override',  # noqa: E501
        'story_links': 'story_links',  # noqa: E501
        'story_type': 'story_type',  # noqa: E501
        'support_tickets': 'support_tickets',  # noqa: E501
        'tasks': 'tasks',  # noqa: E501
        'updated_at': 'updated_at',  # noqa: E501
        'workflow_state_id': 'workflow_state_id',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, name, project_id, *args, **kwargs):  # noqa: E501
        """CreateStoryParams - a model defined in OpenAPI

        Args:
            name (str): The name of the story.
            project_id (int): The ID of the project the story belongs to.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            archived (bool): Controls the story's archived state.. [optional]  # noqa: E501
            comments ([CreateStoryCommentParams]): An array of comments to add to the story.. [optional]  # noqa: E501
            completed_at_override (datetime): A manual override for the time/date the Story was completed.. [optional]  # noqa: E501
            created_at (datetime): The time/date the Story was created.. [optional]  # noqa: E501
            deadline (datetime, none_type): The due date of the story.. [optional]  # noqa: E501
            description (str): The description of the story.. [optional]  # noqa: E501
            epic_id (int, none_type): The ID of the epic the story belongs to.. [optional]  # noqa: E501
            estimate (int, none_type): The numeric point estimate of the story. Can also be null, which means unestimated.. [optional]  # noqa: E501
            external_id (str): This field can be set to another unique ID. In the case that the Story has been imported from another tool, the ID in the other tool can be indicated here.. [optional]  # noqa: E501
            external_links ([str]): An array of External Links associated with this story.. [optional]  # noqa: E501
            external_tickets ([CreateExternalTicketParams]): An array of External Tickets associated with this story. These External Tickets must have unquie external id. Duplicated External Tickets will be removed.. [optional]  # noqa: E501
            file_ids ([int]): An array of IDs of files attached to the story.. [optional]  # noqa: E501
            follower_ids ([str]): An array of UUIDs of the followers of this story.. [optional]  # noqa: E501
            group_id (str, none_type): The id of the group to associate with this story.. [optional]  # noqa: E501
            iteration_id (int, none_type): The ID of the iteration the story belongs to.. [optional]  # noqa: E501
            labels ([CreateLabelParams]): An array of labels attached to the story.. [optional]  # noqa: E501
            linked_file_ids ([int]): An array of IDs of linked files attached to the story.. [optional]  # noqa: E501
            owner_ids ([str]): An array of UUIDs of the owners of this story.. [optional]  # noqa: E501
            requested_by_id (str): The ID of the member that requested the story.. [optional]  # noqa: E501
            started_at_override (datetime): A manual override for the time/date the Story was started.. [optional]  # noqa: E501
            story_links ([CreateStoryLinkParams]): An array of story links attached to the story.. [optional]  # noqa: E501
            story_type (str): The type of story (feature, bug, chore).. [optional]  # noqa: E501
            support_tickets ([CreateExternalTicketParams]): [optional]  # noqa: E501
            tasks ([CreateTaskParams]): An array of tasks connected to the story.. [optional]  # noqa: E501
            updated_at (datetime): The time/date the Story was updated.. [optional]  # noqa: E501
            workflow_state_id (int): The ID of the workflow state the story will be in.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.name = name
        self.project_id = project_id
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
