"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from clubhouse_python_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class File(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'content_type': (str,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'description': (str, none_type,),  # noqa: E501
            'entity_type': (str,),  # noqa: E501
            'external_id': (str, none_type,),  # noqa: E501
            'filename': (str,),  # noqa: E501
            'group_mention_ids': ([str],),  # noqa: E501
            'id': (int,),  # noqa: E501
            'member_mention_ids': ([str],),  # noqa: E501
            'mention_ids': ([str],),  # noqa: E501
            'name': (str,),  # noqa: E501
            'size': (int,),  # noqa: E501
            'story_ids': ([int],),  # noqa: E501
            'thumbnail_url': (str, none_type,),  # noqa: E501
            'updated_at': (datetime, none_type,),  # noqa: E501
            'uploader_id': (str,),  # noqa: E501
            'url': (str, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'content_type': 'content_type',  # noqa: E501
        'created_at': 'created_at',  # noqa: E501
        'description': 'description',  # noqa: E501
        'entity_type': 'entity_type',  # noqa: E501
        'external_id': 'external_id',  # noqa: E501
        'filename': 'filename',  # noqa: E501
        'group_mention_ids': 'group_mention_ids',  # noqa: E501
        'id': 'id',  # noqa: E501
        'member_mention_ids': 'member_mention_ids',  # noqa: E501
        'mention_ids': 'mention_ids',  # noqa: E501
        'name': 'name',  # noqa: E501
        'size': 'size',  # noqa: E501
        'story_ids': 'story_ids',  # noqa: E501
        'thumbnail_url': 'thumbnail_url',  # noqa: E501
        'updated_at': 'updated_at',  # noqa: E501
        'uploader_id': 'uploader_id',  # noqa: E501
        'url': 'url',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, content_type, created_at, description, entity_type, external_id, filename, group_mention_ids, id, member_mention_ids, mention_ids, name, size, story_ids, thumbnail_url, updated_at, uploader_id, url, *args, **kwargs):  # noqa: E501
        """File - a model defined in OpenAPI

        Args:
            content_type (str): Free form string corresponding to a text or image file.
            created_at (datetime): The time/date that the file was created.
            description (str, none_type): The description of the file.
            entity_type (str): A string description of this resource.
            external_id (str, none_type): This field can be set to another unique ID. In the case that the File has been imported from another tool, the ID in the other tool can be indicated here.
            filename (str): The name assigned to the file in Clubhouse upon upload.
            group_mention_ids ([str]): The unique IDs of the Groups who are mentioned in the file description.
            id (int): The unique ID for the file.
            member_mention_ids ([str]): The unique IDs of the Members who are mentioned in the file description.
            mention_ids ([str]): Deprecated: use member_mention_ids.
            name (str): The optional User-specified name of the file.
            size (int): The size of the file.
            story_ids ([int]): The unique IDs of the Stories associated with this file.
            thumbnail_url (str, none_type): The url where the thumbnail of the file can be found in Clubhouse.
            updated_at (datetime, none_type): The time/date that the file was updated.
            uploader_id (str): The unique ID of the Member who uploaded the file.
            url (str, none_type): The URL for the file.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.content_type = content_type
        self.created_at = created_at
        self.description = description
        self.entity_type = entity_type
        self.external_id = external_id
        self.filename = filename
        self.group_mention_ids = group_mention_ids
        self.id = id
        self.member_mention_ids = member_mention_ids
        self.mention_ids = mention_ids
        self.name = name
        self.size = size
        self.story_ids = story_ids
        self.thumbnail_url = thumbnail_url
        self.updated_at = updated_at
        self.uploader_id = uploader_id
        self.url = url
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
