"""
    Clubhouse API

    Clubhouse API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from clubhouse_python_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from clubhouse_python_sdk.model.create_label_params import CreateLabelParams
    globals()['CreateLabelParams'] = CreateLabelParams


class UpdateStory(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('move_to',): {
            'FIRST': "first",
            'LAST': "last",
        },
        ('story_type',): {
            'BUG': "bug",
            'CHORE': "chore",
            'FEATURE': "feature",
        },
    }

    validations = {
        ('branch_ids',): {
        },
        ('commit_ids',): {
        },
        ('file_ids',): {
        },
        ('follower_ids',): {
        },
        ('linked_file_ids',): {
        },
        ('owner_ids',): {
        },
        ('pull_request_ids',): {
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'after_id': (int,),  # noqa: E501
            'archived': (bool,),  # noqa: E501
            'before_id': (int,),  # noqa: E501
            'branch_ids': ([int],),  # noqa: E501
            'commit_ids': ([int],),  # noqa: E501
            'completed_at_override': (datetime, none_type,),  # noqa: E501
            'deadline': (datetime, none_type,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'epic_id': (int, none_type,),  # noqa: E501
            'estimate': (int, none_type,),  # noqa: E501
            'external_links': ([str],),  # noqa: E501
            'file_ids': ([int],),  # noqa: E501
            'follower_ids': ([str],),  # noqa: E501
            'group_id': (str, none_type,),  # noqa: E501
            'iteration_id': (int, none_type,),  # noqa: E501
            'labels': ([CreateLabelParams],),  # noqa: E501
            'linked_file_ids': ([int],),  # noqa: E501
            'move_to': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'owner_ids': ([str],),  # noqa: E501
            'project_id': (int,),  # noqa: E501
            'pull_request_ids': ([int],),  # noqa: E501
            'requested_by_id': (str,),  # noqa: E501
            'started_at_override': (datetime, none_type,),  # noqa: E501
            'story_type': (str,),  # noqa: E501
            'workflow_state_id': (int,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'after_id': 'after_id',  # noqa: E501
        'archived': 'archived',  # noqa: E501
        'before_id': 'before_id',  # noqa: E501
        'branch_ids': 'branch_ids',  # noqa: E501
        'commit_ids': 'commit_ids',  # noqa: E501
        'completed_at_override': 'completed_at_override',  # noqa: E501
        'deadline': 'deadline',  # noqa: E501
        'description': 'description',  # noqa: E501
        'epic_id': 'epic_id',  # noqa: E501
        'estimate': 'estimate',  # noqa: E501
        'external_links': 'external_links',  # noqa: E501
        'file_ids': 'file_ids',  # noqa: E501
        'follower_ids': 'follower_ids',  # noqa: E501
        'group_id': 'group_id',  # noqa: E501
        'iteration_id': 'iteration_id',  # noqa: E501
        'labels': 'labels',  # noqa: E501
        'linked_file_ids': 'linked_file_ids',  # noqa: E501
        'move_to': 'move_to',  # noqa: E501
        'name': 'name',  # noqa: E501
        'owner_ids': 'owner_ids',  # noqa: E501
        'project_id': 'project_id',  # noqa: E501
        'pull_request_ids': 'pull_request_ids',  # noqa: E501
        'requested_by_id': 'requested_by_id',  # noqa: E501
        'started_at_override': 'started_at_override',  # noqa: E501
        'story_type': 'story_type',  # noqa: E501
        'workflow_state_id': 'workflow_state_id',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """UpdateStory - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            after_id (int): The ID of the story we want to move this story after.. [optional]  # noqa: E501
            archived (bool): True if the story is archived, otherwise false.. [optional]  # noqa: E501
            before_id (int): The ID of the story we want to move this story before.. [optional]  # noqa: E501
            branch_ids ([int]): An array of IDs of Branches attached to the story.. [optional]  # noqa: E501
            commit_ids ([int]): An array of IDs of Commits attached to the story.. [optional]  # noqa: E501
            completed_at_override (datetime, none_type): A manual override for the time/date the Story was completed.. [optional]  # noqa: E501
            deadline (datetime, none_type): The due date of the story.. [optional]  # noqa: E501
            description (str): The description of the story.. [optional]  # noqa: E501
            epic_id (int, none_type): The ID of the epic the story belongs to.. [optional]  # noqa: E501
            estimate (int, none_type): The numeric point estimate of the story. Can also be null, which means unestimated.. [optional]  # noqa: E501
            external_links ([str]): An array of External Links associated with this story.. [optional]  # noqa: E501
            file_ids ([int]): An array of IDs of files attached to the story.. [optional]  # noqa: E501
            follower_ids ([str]): An array of UUIDs of the followers of this story.. [optional]  # noqa: E501
            group_id (str, none_type): The ID of the group to associate with this story. [optional]  # noqa: E501
            iteration_id (int, none_type): The ID of the iteration the story belongs to.. [optional]  # noqa: E501
            labels ([CreateLabelParams]): An array of labels attached to the story.. [optional]  # noqa: E501
            linked_file_ids ([int]): An array of IDs of linked files attached to the story.. [optional]  # noqa: E501
            move_to (str): [optional]  # noqa: E501
            name (str): The title of the story.. [optional]  # noqa: E501
            owner_ids ([str]): An array of UUIDs of the owners of this story.. [optional]  # noqa: E501
            project_id (int): The ID of the project the story belongs to.. [optional]  # noqa: E501
            pull_request_ids ([int]): An array of IDs of Pull/Merge Requests attached to the story.. [optional]  # noqa: E501
            requested_by_id (str): The ID of the member that requested the story.. [optional]  # noqa: E501
            started_at_override (datetime, none_type): A manual override for the time/date the Story was started.. [optional]  # noqa: E501
            story_type (str): The type of story (feature, bug, chore).. [optional]  # noqa: E501
            workflow_state_id (int): The ID of the workflow state to put the story in.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
